version: 1.0.{build}

image:
  - Previous Ubuntu1804
  - macOS

environment:
  matrix:
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39

build: off

install:
  - "python3 -m pip install wheel tox tox-appveyor"

test_script:
  - "python3 -m tox"
